# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Gloomy Corner
email: 2ywg63a4h@mozmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Heyyy, welcome to my gloomy corner. Posting all about me: Bicks Tang, and my friend San-San.
baseurl: "" # the subpath of your site, e.g. /blog
imageurl: "/assets/images/"
videourl: "/assets/videos/" # the subpath to your images, e.g. /assets/images
url: "https://mygloomycorner.com" # the base hostname & protocol for your site, e.g. http://example.com

linktree_url: vitimesthree
github_username:  vitimesthree

image: banner.png

defaults:
  # Set default layout for all pages
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "uploads"
    values:
      layout: "archiveView"

# Comic collection
collections:
  uploads:
    output: true
    permalink: archive/polygraph/:name-:slug

# Build settings
# theme: minima
# plugins:
#   - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
